apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.shipment.plans
  labels:
    eventstreams.ibm.com/cluster: eda-dev
spec:
  partitions: 1
  replicas: 3

---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: reefer.telemetries
  labels:
    eventstreams.ibm.com/cluster: eda-dev
spec:
  partitions: 3
  replicas: 3

---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: test
  labels:
    eventstreams.ibm.com/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.inventory
  labels:
    eventstreams.ibm.com/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.transportation
  labels:
    eventstreams.ibm.com/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.reefers
  labels:
    eventstreams.ibm.com/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.reeferalerts
  labels:
    eventstreams.ibm.com/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
