apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: vaccine-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  bootstrapServers: "vaccine-kafka-kafka-bootstrap:9093"
  image: quay.io/ibmcase/kafka-connect-postgres
  authentication:
    certificateAndKey:
      certificate: user.crt
      key: user.key
      secretName: tls-user
    type: tls
  version: 2.7.0
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-ca-cert
        certificate: ca.crt
  replicas: 1
  config:
    group.id: vaccine-connect-cluster
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    offset.storage.topic: vaccine-connect-cluster-offsets
    config.storage.topic: vaccine-connect-cluster-configs
    status.storage.topic: vaccine-connect-cluster-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  tasksMax: 3
  externalConfiguration:
    volumes:
      - name: postgres-connector
        secret:
          secretName: postgres-connector